//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW4GraderPayApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grader
    {
        public int GraderID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public decimal HourlyPay { get; set; }
        public int Hours { get; set; }
        public decimal Stipend { get; set; }
        public string Department { get; set; }


        
        public virtual Department Department1 { get; set; }

        virtual public decimal GetPayment()
        {
            return (HourlyPay * Hours) + Stipend;
        }

    }
}
